### ISSUE TITLE
Installing this dependency breaks Yarn

### ISSUE THREAD

**Issue by yannbf** [thednp/position-observer#1]
Hey @thednp I noticed that since a recent release, this package is using a github url notation to install its dependency:
https://github.com/thednp/position-observer/blob/main/package.json#L54

which causes Yarn to break. How to reproduce:

Run:
```
yarn add @thednp/position-observer     
```

And see Yarn crash:
```     
➤ YN0000: · Yarn 4.2.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @thednp/shorty@https://github.com/thednp/shorty.git#commit=1453fc6b7c9d7df1f8854146921082175dbc99a5: Assertion failed: Unsupported workflow
    at /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:189:1611
    at async Tn.mktempPromise (/Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:9:44849)
    at async /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:186:56
    at async Tn.mktempPromise (/Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:9:44849)
    at async /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:181:3066
➤ YN0000: └ Completed in 2s 435ms
➤ YN0000: · Failed with errors in 2s 441ms
```

Would it be possible to resort to normal semver in the dependency range? Thank you!

**Comment by thednp** [comment]
please test 1.0.3

**Comment by yannbf** [comment]
Thank you so much @thednp, the issue is now resolved 👏 <3
